# Generated by Django 2.1.7 on 2019-04-22 07:19

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('grade_received', models.CharField(default='Select Grade', max_length=15)),
                ('course_review', models.TextField(default='---')),
                ('teacher_review', models.TextField(default='---')),
                ('study_material', models.TextField(default='---')),
                ('quality_rating', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('quantity_rating', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('level_of_difficulty_rating', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('take_again', models.BooleanField(default=False)),
                ('tough_grader', models.BooleanField(default=False)),
                ('self_study_required', models.BooleanField(default=False)),
                ('participation_matters', models.BooleanField(default=False)),
                ('lot_of_assignment', models.BooleanField(default=False)),
                ('accessible_outside_class', models.BooleanField(default=False)),
                ('skip_class_you_dont_pass', models.BooleanField(default=False)),
                ('impartial', models.BooleanField(default=False)),
                ('test_heavy', models.BooleanField(default=False)),
                ('amazing_lectures', models.BooleanField(default=False)),
                ('lecture_heavy', models.BooleanField(default=False)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(default='', max_length=100)),
                ('quality', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('level_of_difficulty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('take_again', models.IntegerField(default=0)),
                ('tough_grader', models.IntegerField(default=0)),
                ('self_study_required', models.IntegerField(default=0)),
                ('participation_matters', models.IntegerField(default=0)),
                ('lot_of_assignment', models.IntegerField(default=0)),
                ('accessible_outside_class', models.IntegerField(default=0)),
                ('skip_class_you_dont_pass', models.IntegerField(default=0)),
                ('impartial', models.IntegerField(default=0)),
                ('test_heavy', models.IntegerField(default=0)),
                ('amazing_lectures', models.IntegerField(default=0)),
                ('lecture_heavy', models.IntegerField(default=0)),
                ('total_reviews', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Teacher'),
        ),
    ]
